### ISSUE TITLE
add support for file:// URL construct

### ISSUE THREAD

**Issue by reikred** [dhondta/webgrep#4]
Seems to me that it would make sense for webgrep to understand local file URL constructs such as file:///tmp/somefile.html , so as to avoid repetitive server requests and slow operation when doing multiple searches, especially on large flat html files. I imagine it should not be a big hack to support file://  for someone that knows the code?

(Motivational background:

I did a webgrep on a large flat webpage that appears to be generated upon request at the server. This was a  very slow process, maybe 33sec CPU time, but I am not sure how much of it was server+download time versus grep time. 

So I downloaded the big flat html file so I could do a local run. BUT webgrep does not support it. I ran a local egrep with the same search term and it finished within 0.01 seconds. So it was probably server time that dominated, and it could be avoided by searching on a local downloaded file)

**Comment by dhondta** [comment]
Hi @reikred !

Thank you for the heads up. However, please beware that : 
- The whole process may be long as, each time a resource is downloaded, it is prepared for grepping (e.g. the Tesseract OCR will run on an image before grepping its results and going further with other resources).
- If you expect the sources to be big and you want to use them later, you can use the `--keep-files` option to cache the results in `/tmp/webrep`. Then, re-webgrepping will call the resource from this cache while targeting the same URL. In other terms, no need to grep on the local resource.

Anyway, your idea is excellent and I thus implemented the support for local file read.

You can `pip install --upgrade webgrep-tool` to version 1.15. Please test and report if any other issue.
Thank you !
